### ISSUE TITLE
How to suppress the [Qibo 0.2.0|INFO outpputs?

### ISSUE THREAD

**Issue by Landau1908** [qiboteam/qibo#1528] opened 2024-11-21 03:11 UTC
Hi, 
When I run a for loop, there outputs large amounts of `[Qibo 0.2.0|INFO` which gives a messy display. How to suppress the [Qibo 0.2.0|INFO outpputs?
Regards

```python
[Qibo 0.2.0|INFO|2024-11-21 08:54:38]: Using qibojit (cupy) backend on /GPU:0
[Qibo 0.2.0|INFO|2024-11-21 08:54:38]: Using qibojit (cupy) backend on /GPU:0
[Qibo 0.2.0|INFO|2024-11-21 08:54:38]: Using qibojit (cupy) backend on /GPU:0
[Qibo 0.2.0|INFO|2024-11-21 08:54:38]: Using qibojit (cupy) backend on /GPU:0
...
```

**Comment by scarrazza** [comment] 2024-11-21 04:14
@Landau1908, please update your Qibo version to the latest release and try your code again.

**Comment by Landau1908** [comment] 2024-11-22 01:30
> @Landau1908, please update your Qibo version to the latest release and try your code again.

Qibo 0.2.13 gives the same outputs. Is there any options to close the outputs?

**Comment by scarrazza** [comment] 2024-11-22 07:34
Could you please provide a minimal example of your code so that I can understand why this message is raised multiple times?

**Comment by alecandido** [comment] 2024-11-24 20:35
Hi @Landau1908: here you are receiving a log message each time you're setting the backend. This is triggered by this line:
https://github.com/qiboteam/qibo/blob/ea6984d7594f403eeadc1e39ebbe0312a8f02716/src/qibo/backends/__init__.py#L119

An easy way to avoid that would be to check the existence and identity of the current global backend (using the `get_backend()` function), before attempting to set it again.

In any case, if you use the `set_backend()` function, that will act globally, so you do not need to set it again (unless you want to set an actually different backend). Otherwise, if you prefer to use local entities, you could just construct the backend, and pass it by value (to directly use `backend.execute_circuit()` for execution).

In case you still have doubts or observation, do not hesitate to reply!

**Comment by marekgluza** [comment] 2024-11-26 00:54
Hi @Landau1908 

can you try this?

```py
import qibo
def qibo_test(backend, platform, threadsNumber):
    qibo.set_backend(backend, platform=platform)
    qibo.set_threads(threadsNumber)
    
if __name__ == "__main__":
    backend = "qibojit"
    platform = "numba"
    threadsNumber = 1
    for _ in range(3):
        qibo_test(backend, platform, threadsNumber)
        
    import logging
    class SpecificWarningFilter(logging.Filter):
        def filter(self, record):
            return (
                "Using qibojit (numba) backend on"
                not in record.getMessage()
            )


    qibo_logger = qibo.config.log
    qibo_logger.addFilter(SpecificWarningFilter())
    
    for _ in range(3):
        qibo_test(backend, platform, threadsNumber)
```

(Props to @MatteoRobbiati via the boostvqe repo)

**Comment by alecandido** [comment] 2024-11-26 04:31
You can always use the env var in order to drop all the info logs:
```sh
# in the same shell in which you run your script
export QIBO_LOG_LEVEL=3
```

Anything `>= 2` will drop all the info logs.

**Comment by MatteoRobbiati** [comment] 2024-11-26 08:20
> Hi @Landau1908
> 
> can you try this?
> 
> ```python
> import qibo
> def qibo_test(backend, platform, threadsNumber):
>     qibo.set_backend(backend, platform=platform)
>     qibo.set_threads(threadsNumber)
>     
> if __name__ == "__main__":
>     backend = "qibojit"
>     platform = "numba"
>     threadsNumber = 1
>     for _ in range(3):
>         qibo_test(backend, platform, threadsNumber)
>         
>     import logging
>     class SpecificWarningFilter(logging.Filter):
>         def filter(self, record):
>             return (
>                 "Using qibojit (numba) backend on"
>                 not in record.getMessage()
>             )
> 
> 
>     qibo_logger = qibo.config.log
>     qibo_logger.addFilter(SpecificWarningFilter())
>     
>     for _ in range(3):
>         qibo_test(backend, platform, threadsNumber)
> ```
> 
> (Props to @MatteoRobbiati via the boostvqe repo)

This is a valid option if you want to suppress some specific info/warning, while keeping the logging level active for the same kind of info/warnings. 
In the case presented above, I would suggest to use the env var as proposed by @alecandido.

**Comment by Landau1908** [comment] 2024-11-26 13:43
Thank you @marekgluza  @MatteoRobbiati @alecandido @scarrazza .
`SpecificWarningFilter` solved the problem.

**Comment by alecandido** [comment] 2024-11-26 14:19
@Landau1908 great to hear it solved your problem :)

If that is working as intended, feel free to close the issue ^^

**Closed** 2024-11-28 09:05 UTC
